export const localitati = {
  Alba: ["Alba Iulia", "Sebeș", "Aiud", "Cugir", "Ocna Mureș", "Abrud"],
  Arad: ["Arad", "Ineu", "Lipova", "Curtici", "Pâncota"],
  Argeș: ["Pitești", "Câmpulung", "Mioveni", "Curtea de Argeș", "Topoloveni"],
  Bacău: ["Bacău", "Onești", "Moinești", "Comănești", "Dărmănești"],
  Bihor: ["Oradea", "Marghita", "Salonta", "Beiuș", "Săcueni"],
  Bistrița_Năsăud: ["Bistrița", "Năsăud", "Sângeorz-Băi"],
  Botoșani: ["Botoșani", "Dorohoi", "Darabani"],
  Brăila: ["Brăila", "Ianca", "Făurei"],
  Brașov: ["Brașov", "Săcele", "Făgăraș", "Râșnov", "Codlea"],
  București: [
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
  ],
  Buzău: ["Buzău", "Râmnicu Sărat", "Nehoiu", "Pogoanele"],
  Călărași: ["Călărași", "Oltenița", "Fundulea"],
  "Caraș-Severin": ["Reșița", "Caransebeș", "Oravița", "Bocșa"],
  Cluj: ["Cluj-Napoca", "Turda", "Dej", "Câmpia Turzii", "Gherla"],
  Constanța: ["Constanța", "Mangalia", "Medgidia", "Năvodari", "Eforie"],
  Covasna: ["Sfântu Gheorghe", "Târgu Secuiesc", "Covasna"],
  Dâmbovița: ["Târgoviște", "Moreni", "Fieni", "Pucioasa", "Găești"],
  Dolj: ["Craiova", "Calafat", "Băilești", "Dăbuleni", "Filiași"],
  Galați: ["Galați", "Tecuci", "Târgu Bujor", "Berești"],
  Giurgiu: ["Giurgiu", "Bolintin-Vale", "Mihăilești"],
  Gorj: ["Târgu Jiu", "Motru", "Rovinari"],
  Harghita: ["Miercurea Ciuc", "Odorheiu Secuiesc", "Gheorgheni"],
  Hunedoara: ["Deva", "Hunedoara", "Lupeni", "Brad", "Petroșani"],
  Ialomița: ["Slobozia", "Fetești", "Urziceni"],
  Iași: ["Iași", "Pașcani", "Târgu Frumos", "Hârlău"],
  Ilfov: ["Otopeni", "Voluntari", "Măgurele", "Buftea"],
  Maramureș: ["Baia Mare", "Sighetu Marmației", "Borșa", "Vișeu de Sus"],
  Mehedinți: ["Drobeta-Turnu Severin", "Orșova", "Strehaia"],
  Mureș: ["Târgu Mureș", "Reghin", "Sighișoara", "Târnăveni"],
  Neamț: ["Piatra Neamț", "Roman", "Târgu Neamț", "Roznov"],
  Olt: ["Slatina", "Corabia", "Scornicești", "Balș"],
  Prahova: ["Ploiești", "Câmpina", "Sinaia", "Vălenii de Munte"],
  Sălaj: ["Zalău", "Șimleu Silvaniei", "Jibou"],
  "Satu Mare": ["Satu Mare", "Carei", "Negrești-Oaș"],
  Sibiu: ["Sibiu", "Mediaș", "Agnita", "Cisnădie"],
  Suceava: ["Suceava", "Rădăuți", "Fălticeni", "Câmpulung Moldovenesc"],
  Teleorman: ["Alexandria", "Roșiorii de Vede", "Zimnicea"],
  Timiș: [
    "Timișoara",
    "Lugoj",
    "Sânnicolau Mare",
    "Recaș",
    "Jimbolia",
    "Făget",
    "Deta",
    "Gătaia",
    "Buziaș",
    "Dumbrăvița",
    "Sânmihaiu Român",
    "Sânandrei",
    "Sacoșu Turcesc",
    "Chevereșu Mare",
    "Giarmata",
    "Moșnița Nouă",
    "Ghiroda",
    "Coșteiu",
    "Sânpetru Mare",
    "Orțișoara",
    "Parța",
    "Comloșu Mare",
    "Otelec",
    "Jebel",
  ],
  Tulcea: ["Tulcea", "Babadag", "Măcin"],
  Vâlcea: ["Râmnicu Vâlcea", "Drăgășani", "Călimănești"],
  Vaslui: ["Vaslui", "Huși", "Negrești"],
  Vrancea: ["Focșani", "Mărășești", "Adjud"],
};
